variables:
- group: trading-db-vars

trigger:
- main

pool:
  name: Default   # your self-hosted pool

variables:
  SA_PASSWORD: $(SA_PASSWORD)   # set as secret variable in the pipeline or a variable group

stages:
- stage: Deploy_DB
  jobs:
  - job: up_compose
    displayName: Docker Compose Up (DB + Flyway)
    steps:
    - checkout: self
      clean: true

    # Ensure target dir exists and write .env (keeps SA secret out of repo)
    - script: |
        set -euo pipefail
        # Ensure the secret reached the job
        if [ -z "${SA_PASSWORD:-}" ]; then
          echo "ERROR: SA_PASSWORD is empty. Did you authorize the variable group or mark the variable as secret?" >&2
          exit 1
        fi

        mkdir -p docker
        # Never echo secrets to logs; write directly to file
        printf "SA_PASSWORD=%s\n" "$SA_PASSWORD" > docker/.env

        # Convert to LF endings just in case this runs on Windows agents later
        if command -v dos2unix >/dev/null 2>&1; then dos2unix docker/.env || true; fi

        # Quick sanity (don’t print the secret)
        echo "Wrote docker/.env (length=$(wc -c < docker/.env) bytes)"
      displayName: "Create .env with SA_PASSWORD"
      env:
        SA_PASSWORD: $(SA_PASSWORD)

    # Bring up stack using the compose in repo
    - script: |
        set -euo pipefail
        cd docker
        docker compose pull || true
        docker compose up -d
        docker compose ps
      displayName: "docker compose up -d"

    # Show Flyway output & smoke test
    - script: |
        set -euo pipefail

        # Wait until the SQL container is healthy
        echo "Waiting for trading-mssql to be healthy..."
        for i in {1..30}; do
          STATUS=$(docker inspect --format '{{.State.Health.Status}}' trading-mssql || echo "unknown")
          if [ "$STATUS" = "healthy" ]; then
            echo "OK: trading-mssql is healthy."
            break
          fi
          echo "Current status: $STATUS (attempt $i/30)"; sleep 3
          if [ $i -eq 30 ]; then
            echo "ERROR: SQL container not healthy in time"; exit 1
          fi
        done

        # Show last part of Flyway logs
        echo "==== Flyway logs (tail) ===="
        docker compose -f docker/docker-compose.yml logs --no-color flyway | tail -n 200 || true

        # Use the SA password from the environment (note: $SA_PASSWORD, not $(SA_PASSWORD))
        PW="$SA_PASSWORD"

        # Run smoke queries *inside* the SQL container
        docker exec trading-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$PW" -C -Q "SELECT name FROM sys.databases;"
        docker exec trading-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$PW" -C -Q "USE trading; SELECT name FROM sys.tables ORDER BY name;"
        docker exec trading-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$PW" -C -Q "USE trading; SELECT installed_rank,version,description,success FROM dbo.flyway_schema_history ORDER BY installed_rank;"
      displayName: "Verify DB & migrations"
      env:
        SA_PASSWORD: $(SA_PASSWORD)
