trigger:
- main

pool:
  name: Default   # your self-hosted pool

variables:
  SA_PASSWORD: $(SA_PASSWORD)   # set as secret variable in the pipeline or a variable group

stages:
- stage: Deploy_DB
  jobs:
  - job: up_compose
    displayName: Docker Compose Up (DB + Flyway)
    steps:
    - checkout: self
      clean: true

    # Ensure target dir exists and write .env (keeps SA secret out of repo)
    - script: |
        mkdir -p $(Build.SourcesDirectory)/docker
        echo SA_PASSWORD=$(SA_PASSWORD) > $(Build.SourcesDirectory)/docker/.env
      displayName: "Create .env with SA_PASSWORD"

    # Bring up stack using the compose in repo
    - script: |
        cd docker
        docker compose pull || true
        docker compose up -d
        docker compose ps
      displayName: "docker compose up -d"

    # Show Flyway output & smoke test
    - script: |
        cd docker
        docker compose logs --no-color flyway | tail -n 200
        docker exec trading-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$(SA_PASSWORD)" -C -Q "SELECT name FROM sys.databases;"
        docker exec trading-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$(SA_PASSWORD)" -C -Q "USE trading; SELECT name FROM sys.tables ORDER BY name;"
        docker exec trading-mssql /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$(SA_PASSWORD)" -C -Q "USE trading; SELECT installed_rank,version,description,success FROM dbo.flyway_schema_history ORDER BY installed_rank;"
      displayName: "Verify DB & migrations"
