services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: trading-mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "/opt/mssql-tools18/bin/sqlcmd", "-S", "localhost,1433", "-U", "sa", "-P", "${SA_PASSWORD}", "-C", "-Q", "SELECT 1"]
      interval: 10s
      timeout: 3s
      retries: 10

  db-bootstrap:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      mssql:
        condition: service_healthy
    entrypoint: ["/bin/bash","-lc"]
    command: >
      "/opt/mssql-tools18/bin/sqlcmd -S mssql,1433 -U sa -P ${SA_PASSWORD} -C
      -Q \"IF DB_ID('trading') IS NULL CREATE DATABASE trading;\""

  flyway:
    image: flyway/flyway:10
    depends_on:
      db-bootstrap:
        condition: service_completed_successfully
    volumes:
      - ../migrations:/flyway/sql
    command:
      - -url=jdbc:sqlserver://mssql:1433;database=trading;encrypt=true;trustServerCertificate=true
      - -user=sa
      - -password=${SA_PASSWORD}
      - -locations=filesystem:/flyway/sql
      - -baselineOnMigrate=true
      - migrate

volumes:
  mssql_data:
